version: "1"

services:
  redis:
    image: redis:latest
    container_name: redis-tinyurl
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  redis_data:
    driver: local
